apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: install component
inputs:
  version:  
    description: component version or image tag
    required: true
outputs: 
runs:
  using: composite
  steps:
    - name: Install component
      uses: docker://golang:1.20.3-alpine3.17
      shell: sh
      run: echo installing component "${{ cloudbees.scm.repository }}" version "${{ inputs.version }}"
